version: '3.7'

services:
    web:
        build:
            context: ./
            target: flask
        expose:
            - 5000

    nginx:
        build:
            context: ./
            target: nginx
        ports:
            - 3000:80